"""
SkillGraph data models — all Pydantic schemas in one place.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Skill Extraction Models (used by AI service)
# ---------------------------------------------------------------------------

class ExtractedSkill(BaseModel):
    """A single skill extracted from a resume or job description."""

    name: str = Field(description="Canonical skill name, e.g. 'React', 'Python', 'SEO'")
    category: str = Field(
        description="One of: technical, soft, domain, tool, certification"
    )
    level: str = Field(
        description="Proficiency or requirement level: beginner, intermediate, advanced"
    )


class ResumeAnalysis(BaseModel):
    """Result of extracting skills from a user's resume."""

    skills: list[ExtractedSkill] = Field(description="List of skills found in the resume")
    summary: str = Field(description="Brief 2-3 sentence professional summary of the candidate")


class RoleSkillRequirements(BaseModel):
    """Skills required for a target role, generated by AI."""

    role_title: str = Field(description="Normalized role title")
    role_category: str = Field(
        description="Broad category, e.g. 'Technology', 'Marketing', 'Finance'"
    )
    seniority: str = Field(description="Typical seniority: Entry-Level, Mid, Senior")
    skills: list[ExtractedSkill] = Field(description="Skills required for the role")


# ---------------------------------------------------------------------------
# Gap Analysis Models
# ---------------------------------------------------------------------------

class SkillMatch(BaseModel):
    """A skill that matched between user and role requirements."""

    name: str
    user_level: str
    required_level: str


class GapResult(BaseModel):
    """Result of comparing user skills against role requirements."""

    matched_skills: list[SkillMatch] = Field(default_factory=list)
    missing_skills: list[ExtractedSkill] = Field(default_factory=list)
    readiness_score: float = Field(
        description="0.0 to 1.0 indicating how ready the user is for the role"
    )


# ---------------------------------------------------------------------------
# Roadmap Models
# ---------------------------------------------------------------------------

class RoadmapResource(BaseModel):
    """A learning resource for a skill."""

    title: str = Field(description="Name of the resource")
    url: str = Field(description="URL to the resource")
    type: str = Field(description="Type: course, documentation, video, tutorial, book")


class RoadmapSkillDetail(BaseModel):
    """Detailed info about a skill in the roadmap."""

    name: str
    estimated_hours: int = Field(description="Estimated hours to learn this skill")
    description: str = Field(description="Brief description of what to learn")
    resources: list[RoadmapResource] = Field(default_factory=list)


class RoadmapPhase(BaseModel):
    """A phase in the learning roadmap."""

    phase_number: int
    title: str = Field(description="Phase title, e.g. 'Fundamentals'")
    duration_weeks: int
    skills: list[RoadmapSkillDetail] = Field(default_factory=list)


class LearningRoadmap(BaseModel):
    """Complete learning roadmap generated by AI."""

    target_role: str
    total_weeks: int
    phases: list[RoadmapPhase] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# API Response Models
# ---------------------------------------------------------------------------

class AnalysisResponse(BaseModel):
    """Full response from the /api/analyze endpoint."""

    session_id: str
    user_skills: list[ExtractedSkill]
    user_summary: str
    role_requirements: RoleSkillRequirements
    gap: GapResult
    roadmap: LearningRoadmap


class RoleInfo(BaseModel):
    """A role for the role selector dropdown."""

    name: str
    category: str


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = "ok"
    version: str = "0.1.0"
